package model;
// Generated Feb 10, 2016 1:49:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Permission generated by hbm2java
 */
public class Permission  implements java.io.Serializable {


     private Integer permissionId;
     private Authority authority;
     private User user;
     private String email;
     private String authName;
     private String name;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestmap;

    public Permission() {
    }

	
    public Permission(Authority authority, User user, String email, String authName, String name) {
        this.authority = authority;
        this.user = user;
        this.email = email;
        this.authName = authName;
        this.name = name;
    }
    public Permission(Authority authority, User user, String email, String authName, String name, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestmap) {
       this.authority = authority;
       this.user = user;
       this.email = email;
       this.authName = authName;
       this.name = name;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestmap = updatedTimestmap;
    }
   
    public Integer getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
    public Authority getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(Authority authority) {
        this.authority = authority;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAuthName() {
        return this.authName;
    }
    
    public void setAuthName(String authName) {
        this.authName = authName;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestmap() {
        return this.updatedTimestmap;
    }
    
    public void setUpdatedTimestmap(Date updatedTimestmap) {
        this.updatedTimestmap = updatedTimestmap;
    }




}


