package model;
// Generated Feb 10, 2016 1:49:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private Integer storeId;
     private String storeName;
     private String phoneNumber;
     private String description;
     private String reference01;
     private String reference02;
     private String reference03;
     private String reference04;
     private String reference05;
     private String reference06;
     private String reference07;
     private String reference08;
     private String reference09;
     private String reference19;
     private String country;
     private String city;
     private String address01;
     private String address02;
     private String email;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;
     private Set storeProducts = new HashSet(0);

    public Store() {
    }

	
    public Store(String storeName, String phoneNumber, String description) {
        this.storeName = storeName;
        this.phoneNumber = phoneNumber;
        this.description = description;
    }
    public Store(String storeName, String phoneNumber, String description, String reference01, String reference02, String reference03, String reference04, String reference05, String reference06, String reference07, String reference08, String reference09, String reference19, String country, String city, String address01, String address02, String email, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp, Set storeProducts) {
       this.storeName = storeName;
       this.phoneNumber = phoneNumber;
       this.description = description;
       this.reference01 = reference01;
       this.reference02 = reference02;
       this.reference03 = reference03;
       this.reference04 = reference04;
       this.reference05 = reference05;
       this.reference06 = reference06;
       this.reference07 = reference07;
       this.reference08 = reference08;
       this.reference09 = reference09;
       this.reference19 = reference19;
       this.country = country;
       this.city = city;
       this.address01 = address01;
       this.address02 = address02;
       this.email = email;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
       this.storeProducts = storeProducts;
    }
   
    public Integer getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getReference01() {
        return this.reference01;
    }
    
    public void setReference01(String reference01) {
        this.reference01 = reference01;
    }
    public String getReference02() {
        return this.reference02;
    }
    
    public void setReference02(String reference02) {
        this.reference02 = reference02;
    }
    public String getReference03() {
        return this.reference03;
    }
    
    public void setReference03(String reference03) {
        this.reference03 = reference03;
    }
    public String getReference04() {
        return this.reference04;
    }
    
    public void setReference04(String reference04) {
        this.reference04 = reference04;
    }
    public String getReference05() {
        return this.reference05;
    }
    
    public void setReference05(String reference05) {
        this.reference05 = reference05;
    }
    public String getReference06() {
        return this.reference06;
    }
    
    public void setReference06(String reference06) {
        this.reference06 = reference06;
    }
    public String getReference07() {
        return this.reference07;
    }
    
    public void setReference07(String reference07) {
        this.reference07 = reference07;
    }
    public String getReference08() {
        return this.reference08;
    }
    
    public void setReference08(String reference08) {
        this.reference08 = reference08;
    }
    public String getReference09() {
        return this.reference09;
    }
    
    public void setReference09(String reference09) {
        this.reference09 = reference09;
    }
    public String getReference19() {
        return this.reference19;
    }
    
    public void setReference19(String reference19) {
        this.reference19 = reference19;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress01() {
        return this.address01;
    }
    
    public void setAddress01(String address01) {
        this.address01 = address01;
    }
    public String getAddress02() {
        return this.address02;
    }
    
    public void setAddress02(String address02) {
        this.address02 = address02;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
    public Set getStoreProducts() {
        return this.storeProducts;
    }
    
    public void setStoreProducts(Set storeProducts) {
        this.storeProducts = storeProducts;
    }




}


