package model;
// Generated Feb 10, 2016 1:49:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StoreProduct generated by hbm2java
 */
public class StoreProduct  implements java.io.Serializable {


     private Integer storeProductId;
     private Store store;
     private SubCategory subCategory;
     private String storeName;
     private String subcategoryName;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;

    public StoreProduct() {
    }

	
    public StoreProduct(Store store, SubCategory subCategory, String storeName, String subcategoryName) {
        this.store = store;
        this.subCategory = subCategory;
        this.storeName = storeName;
        this.subcategoryName = subcategoryName;
    }
    public StoreProduct(Store store, SubCategory subCategory, String storeName, String subcategoryName, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp) {
       this.store = store;
       this.subCategory = subCategory;
       this.storeName = storeName;
       this.subcategoryName = subcategoryName;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
    }
   
    public Integer getStoreProductId() {
        return this.storeProductId;
    }
    
    public void setStoreProductId(Integer storeProductId) {
        this.storeProductId = storeProductId;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getSubcategoryName() {
        return this.subcategoryName;
    }
    
    public void setSubcategoryName(String subcategoryName) {
        this.subcategoryName = subcategoryName;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }




}


