package model;
// Generated Feb 21, 2016 4:25:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private Integer storeId;
     private String storeName;
     private String storeDescription;
     private String location;
     private String latitude;
     private String longtitude;
     private String country;
     private String city;
     private String phoneNumber;
     private String email;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;
     private Set storeProducts = new HashSet(0);

    public Store() {
    }

	
    public Store(String storeName, String storeDescription, String latitude) {
        this.storeName = storeName;
        this.storeDescription = storeDescription;
        this.latitude = latitude;
    }
    public Store(String storeName, String storeDescription, String location, String latitude, String longtitude, String country, String city, String phoneNumber, String email, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp, Set storeProducts) {
       this.storeName = storeName;
       this.storeDescription = storeDescription;
       this.location = location;
       this.latitude = latitude;
       this.longtitude = longtitude;
       this.country = country;
       this.city = city;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
       this.storeProducts = storeProducts;
    }
   
    public Integer getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getStoreDescription() {
        return this.storeDescription;
    }
    
    public void setStoreDescription(String storeDescription) {
        this.storeDescription = storeDescription;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongtitude() {
        return this.longtitude;
    }
    
    public void setLongtitude(String longtitude) {
        this.longtitude = longtitude;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
    public Set getStoreProducts() {
        return this.storeProducts;
    }
    
    public void setStoreProducts(Set storeProducts) {
        this.storeProducts = storeProducts;
    }




}


