package model;
// Generated Feb 10, 2016 1:49:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer subCategoryId;
     private Category category;
     private String categoryName;
     private String subCategoryName;
     private String description;
     private String reference01;
     private String reference02;
     private String reference03;
     private String reference04;
     private String reference05;
     private String reference06;
     private String reference07;
     private String reference08;
     private String reference09;
     private String reference10;
     private String reference11;
     private String reference12;
     private String reference13;
     private String reference14;
     private String reference15;
     private String reference16;
     private String reference17;
     private String reference18;
     private String reference19;
     private String reference20;
     private double price;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;
     private Set storeProducts = new HashSet(0);

    public SubCategory() {
    }

	
    public SubCategory(Category category, String categoryName, String subCategoryName, String description, double price) {
        this.category = category;
        this.categoryName = categoryName;
        this.subCategoryName = subCategoryName;
        this.description = description;
        this.price = price;
    }
    public SubCategory(Category category, String categoryName, String subCategoryName, String description, String reference01, String reference02, String reference03, String reference04, String reference05, String reference06, String reference07, String reference08, String reference09, String reference10, String reference11, String reference12, String reference13, String reference14, String reference15, String reference16, String reference17, String reference18, String reference19, String reference20, double price, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp, Set storeProducts) {
       this.category = category;
       this.categoryName = categoryName;
       this.subCategoryName = subCategoryName;
       this.description = description;
       this.reference01 = reference01;
       this.reference02 = reference02;
       this.reference03 = reference03;
       this.reference04 = reference04;
       this.reference05 = reference05;
       this.reference06 = reference06;
       this.reference07 = reference07;
       this.reference08 = reference08;
       this.reference09 = reference09;
       this.reference10 = reference10;
       this.reference11 = reference11;
       this.reference12 = reference12;
       this.reference13 = reference13;
       this.reference14 = reference14;
       this.reference15 = reference15;
       this.reference16 = reference16;
       this.reference17 = reference17;
       this.reference18 = reference18;
       this.reference19 = reference19;
       this.reference20 = reference20;
       this.price = price;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
       this.storeProducts = storeProducts;
    }
   
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getReference01() {
        return this.reference01;
    }
    
    public void setReference01(String reference01) {
        this.reference01 = reference01;
    }
    public String getReference02() {
        return this.reference02;
    }
    
    public void setReference02(String reference02) {
        this.reference02 = reference02;
    }
    public String getReference03() {
        return this.reference03;
    }
    
    public void setReference03(String reference03) {
        this.reference03 = reference03;
    }
    public String getReference04() {
        return this.reference04;
    }
    
    public void setReference04(String reference04) {
        this.reference04 = reference04;
    }
    public String getReference05() {
        return this.reference05;
    }
    
    public void setReference05(String reference05) {
        this.reference05 = reference05;
    }
    public String getReference06() {
        return this.reference06;
    }
    
    public void setReference06(String reference06) {
        this.reference06 = reference06;
    }
    public String getReference07() {
        return this.reference07;
    }
    
    public void setReference07(String reference07) {
        this.reference07 = reference07;
    }
    public String getReference08() {
        return this.reference08;
    }
    
    public void setReference08(String reference08) {
        this.reference08 = reference08;
    }
    public String getReference09() {
        return this.reference09;
    }
    
    public void setReference09(String reference09) {
        this.reference09 = reference09;
    }
    public String getReference10() {
        return this.reference10;
    }
    
    public void setReference10(String reference10) {
        this.reference10 = reference10;
    }
    public String getReference11() {
        return this.reference11;
    }
    
    public void setReference11(String reference11) {
        this.reference11 = reference11;
    }
    public String getReference12() {
        return this.reference12;
    }
    
    public void setReference12(String reference12) {
        this.reference12 = reference12;
    }
    public String getReference13() {
        return this.reference13;
    }
    
    public void setReference13(String reference13) {
        this.reference13 = reference13;
    }
    public String getReference14() {
        return this.reference14;
    }
    
    public void setReference14(String reference14) {
        this.reference14 = reference14;
    }
    public String getReference15() {
        return this.reference15;
    }
    
    public void setReference15(String reference15) {
        this.reference15 = reference15;
    }
    public String getReference16() {
        return this.reference16;
    }
    
    public void setReference16(String reference16) {
        this.reference16 = reference16;
    }
    public String getReference17() {
        return this.reference17;
    }
    
    public void setReference17(String reference17) {
        this.reference17 = reference17;
    }
    public String getReference18() {
        return this.reference18;
    }
    
    public void setReference18(String reference18) {
        this.reference18 = reference18;
    }
    public String getReference19() {
        return this.reference19;
    }
    
    public void setReference19(String reference19) {
        this.reference19 = reference19;
    }
    public String getReference20() {
        return this.reference20;
    }
    
    public void setReference20(String reference20) {
        this.reference20 = reference20;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
    public Set getStoreProducts() {
        return this.storeProducts;
    }
    
    public void setStoreProducts(Set storeProducts) {
        this.storeProducts = storeProducts;
    }




}


