package model;
// Generated Feb 10, 2016 1:49:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String fname;
     private String sname;
     private String email;
     private String password;
     private Date birthOfDate;
     private String gender;
     private String country;
     private String city;
     private String address1;
     private String address2;
     private String phoneNumber;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;
     private Set permissions = new HashSet(0);

    public User() {
    }

	
    public User(String fname, String sname, String email, String password, Date birthOfDate) {
        this.fname = fname;
        this.sname = sname;
        this.email = email;
        this.password = password;
        this.birthOfDate = birthOfDate;
    }
    public User(String fname, String sname, String email, String password, Date birthOfDate, String gender, String country, String city, String address1, String address2, String phoneNumber, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp, Set permissions) {
       this.fname = fname;
       this.sname = sname;
       this.email = email;
       this.password = password;
       this.birthOfDate = birthOfDate;
       this.gender = gender;
       this.country = country;
       this.city = city;
       this.address1 = address1;
       this.address2 = address2;
       this.phoneNumber = phoneNumber;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
       this.permissions = permissions;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getBirthOfDate() {
        return this.birthOfDate;
    }
    
    public void setBirthOfDate(Date birthOfDate) {
        this.birthOfDate = birthOfDate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
    public Set getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set permissions) {
        this.permissions = permissions;
    }




}


