package model;
// Generated Feb 21, 2016 4:25:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private Date birthOfDate;
     private String gender;
     private String country;
     private String city;
     private String address01;
     private String address02;
     private String phoneNumber;
     private Integer createdBy;
     private Date createdTimestamp;
     private Integer updatedBy;
     private Date updatedTimestamp;
     private Set userPermissions = new HashSet(0);
     private Set reviews = new HashSet(0);
     private Set comments = new HashSet(0);

    public User() {
    }

	
    public User(String firstName, String lastName, String email, String password, Date birthOfDate, String gender, String country, String city, String address01, String phoneNumber) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.birthOfDate = birthOfDate;
        this.gender = gender;
        this.country = country;
        this.city = city;
        this.address01 = address01;
        this.phoneNumber = phoneNumber;
    }
    public User(String firstName, String lastName, String email, String password, Date birthOfDate, String gender, String country, String city, String address01, String address02, String phoneNumber, Integer createdBy, Date createdTimestamp, Integer updatedBy, Date updatedTimestamp, Set userPermissions, Set reviews, Set comments) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.birthOfDate = birthOfDate;
       this.gender = gender;
       this.country = country;
       this.city = city;
       this.address01 = address01;
       this.address02 = address02;
       this.phoneNumber = phoneNumber;
       this.createdBy = createdBy;
       this.createdTimestamp = createdTimestamp;
       this.updatedBy = updatedBy;
       this.updatedTimestamp = updatedTimestamp;
       this.userPermissions = userPermissions;
       this.reviews = reviews;
       this.comments = comments;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getBirthOfDate() {
        return this.birthOfDate;
    }
    
    public void setBirthOfDate(Date birthOfDate) {
        this.birthOfDate = birthOfDate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress01() {
        return this.address01;
    }
    
    public void setAddress01(String address01) {
        this.address01 = address01;
    }
    public String getAddress02() {
        return this.address02;
    }
    
    public void setAddress02(String address02) {
        this.address02 = address02;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
    public Set getUserPermissions() {
        return this.userPermissions;
    }
    
    public void setUserPermissions(Set userPermissions) {
        this.userPermissions = userPermissions;
    }
    public Set getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set reviews) {
        this.reviews = reviews;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


